export default [
	/// locations
	{ data: { id: 'auris', label: 'Auris en Oisans', type: 'village' } },
		// to: ['Auris Express', 'Piegut'],
	{ data: { id: 'bergers', label: 'Bergers', type: 'village' } },
		// to: ['Alpauris (Huez-Auris)'],
	{ data: { id: 'maronne-village', label: 'Maronne', type: 'village' } },
	{ data: { id: 'fontfroide-picnic', label: 'Fontfroide picnic area', type: 'picnic'} },
		// to: ['Louvets', 'Fontfroide', 'Alpauris (Auris-Gua)'],
	{ data: { id: 'signal-de-lhomme', label: 'Signal de l\'Homme', type: 'viewpoint'} },

	/// junction nodes
	{ data: { id: 'sures-top' }},
		// to: ['Rhodos (top)', 'Jacques le Bucheron'],
	{ data: { id: 'gentianes-col-junction' }},
	{ data: { id: 'maronne-top' }},
	{ data: { id: 'rhodos-farcis-col-junction'}},
		// to: ['Farcis', 'Col (bottom)']
	{ data: { id: 'farcis-fuma-junction'}},
	{ data: { id: 'auris-express-top'}},
	{ data: { id: 'pre-rond-fontfroide-junction'}},
	{ data: { id: 'lys-gua-junction'}},
	{ data: { id: 'gua-sarenne-junction'}},
	{ data: { id: 'lombards-bottom'}},
	{ data: { id: 'lombards-top'}},
	{ data: { id: 'alpauris-bottom'}},
	{ data: { id: 'chalvets-bottom'}},
	{ data: { id: 'charbonniere-campanules-junction'}},
	{ data: { id: 'rosai-pre-rond-junction'}},
	{ data: { id: 'rosai-col-junction'}},

	/// lifts
	{ data: { id: 'sures', label: 'Sures', type: 'telesiege', source: 'auris', target: 'sures-top',} },
	{ data: { id: 'maronne', label: 'Maronne', type: 'telesiege', source: 'maronne-village', target: 'maronne-top',} },
	{ data: { id: 'auris-express', label: 'Auris Express', type: 'telesiege', source: 'auris', target: 'auris-express-top',} },
	{ data: { id: 'louvets', label: 'Lovets', type: 'telesiege', source: 'fontfroide-picnic', target: 'auris-express-top',} },
	{ data: { id: 'lombards', label: 'Lovets', type: 'telesiege', source: 'lombards-bottom', target: 'lombards-top',} },
	{ data: { id: 'alpauris-auris-gua', label: 'Alpauris', type: 'telesiege', source: 'fontfroide-picnic', target: 'alpauris-bottom',} },
	{ data: { id: 'alpauris-gua-bergers', label: 'Alpauris', type: 'telesiege', source: 'alpauris-bottom', target: 'bergers',} },
	{ data: { id: 'alpauris-bergers-auris', label: 'Alpauris', type: 'telesiege', source: 'bergers', target: 'fontfroide-picnic',} },
	{ data: { id: 'chalvets', label: 'Chalvets', type: 'telesiege', source: 'chalvets-bottom', target: 'charbonniere-campanules-junction',} },

	/// runs
	{ data: { id: 'gentianes', label: 'Gentianes', type: 'blue', source: 'sures-top', target: 'gentianes-col-junction',}},
	{ data: { id: 'rhodos-top', label: 'Rhodos', type: 'red', source: 'sures-top', target: 'maronne-top',}},
	{ data: { id: 'col-top', label: 'Col', type: 'blue', source: 'auris-express-top', target: 'gentianes-col-junction'} },
	{ data: { id: 'col-middle', label: 'Col', type: 'blue', source: 'gentianes-col-junction', target: 'rosai-col-junction'} },
	{ data: { id: 'col-bottom', label: 'Col', type: 'blue', source: 'rosai-col-junction', target: 'auris'} },
	{ data: { id: 'rhodos-middle', label: 'Rhodos', type: 'red', source: 'maronne-top', target: 'rhodos-farcis-col-junction',}},
	{ data: { id: 'rhodos-bottom', label: 'Rhodos', type: 'red', source: 'rhodos-farcis-col-junction', target: 'gentianes-col-junction' } },
	{ data: { id: 'fuma', label: 'La Fuma', type: 'black', source: 'maronne-top', target: 'farcis-fuma-junction',}},
	{ data: { id: 'farcis-top', label: 'Farcis', type: 'blue', source: 'rhodos-farcis-col-junction', target: 'farcis-fuma-junction',}},
	{ data: { id: 'farcis-bottom', label: 'Farcis', type: 'blue', source: 'farcis-fuma-junction', target: 'maronne-village',}},
	{ data: { id: 'eterlous', label: 'Eterlous', type: 'blue', source: 'auris-express-top', target: 'fontfroide-picnic', length: 1}},
	{ data: { id: 'demoiselles', label: 'Demoiselles', type: 'green', source: 'auris-express-top', target: 'fontfroide-picnic', length: 2}},
	{ data: { id: 'pre-rond-middle', label: 'Pre-Rond', type: 'blue', source: 'auris-express-top', target: 'pre-rond-fontfroide-junction',}},
	{ data: { id: 'fontfroide-bottom', label: 'Fontfroide', type: 'red', source: 'pre-rond-fontfroide-junction', target: 'fontfroide-picnic',}},
	{ data: { id: 'fontfroide-bottom', label: 'Fontfroide', type: 'red', source: 'pre-rond-fontfroide-junction', target: 'fontfroide-picnic',}},
	{ data: { id: 'fontfroide-top', label: 'Fontfroide', type: 'red', source: 'signal-de-lhomme', target: 'pre-rond-fontfroide-junction',}},
	{ data: { id: 'pre-rond-top', label: 'Pre-rond', type: 'blue', source: 'signal-de-lhomme', target: 'rosai-pre-rond-junction',}},
	{ data: { id: 'pre-rond-top-2', label: 'Pre-rond', type: 'blue', source: 'rosai-pre-rond-junction', target: 'auris-express-top',}},
	{ data: { id: 'pre-rond-bottom', label: 'Pre-rond', type: 'blue', source: 'pre-rond-fontfroide-junction', target: 'fontfroide-picnic',}},
	{ data: { id: 'bergerie', label: 'Bergerie', type: 'black', source: 'signal-de-lhomme', target: 'lys-gua-junction',}},
	{ data: { id: 'gua-top', label: 'Gua', type: 'blue', source: 'pre-rond-fontfroide-junction', target: 'lys-gua-junction',}},
	{ data: { id: 'gua-middle', label: 'Gua', type: 'blue', source: 'lys-gua-junction', target: 'gua-sarenne-junction',}},
	{ data: { id: 'gua-middle-2', label: 'Gua', type: 'blue', source: 'gua-sarenne-junction', target: 'chalvets-bottom',}},
	{ data: { id: 'gua-middle-3', label: 'Gua', type: 'blue', source: 'chalvets-bottom', target: 'lombards-bottom',}},
	{ data: { id: 'gua-bottom', label: 'Gua', type: 'blue', source: 'lombards-bottom', target: 'alpauris-bottom',}},
	{ data: { id: 'lys-top', label: 'Lys', type: 'blue', source: 'lombards-top', target: 'lys-gua-junction',}},
	{ data: { id: 'lys-bottom', label: 'Lys', type: 'blue', source: 'lys-gua-junction', target: 'lombards-bottom',}},
	{ data: { id: 'col-de-cluy', label: 'Col de Cluy', type: 'black', source: 'signal-de-lhomme', target: 'gua-sarenne-junction',}},
	{ data: { id: 'la-mine', label: 'La Mine', type: 'red', source: 'charbonniere-campanules-junction', target: 'chalvets-bottom',}},
	{ data: { id: 'campanules', label: 'Campanules', type: 'red', source: 'charbonniere-campanules-junction', target: 'bergers',}},
	{ data: { id: 'rosai-top', label: 'Rosai', type: 'red', source: 'signal-de-lhomme', target: 'rosai-pre-rond-junction',}},
	{ data: { id: 'rosai-middle', label: 'Rosai', type: 'red', source: 'rosai-pre-rond-junction', target: 'rosai-col-junction',}},
	{ data: { id: 'rosai-bottom', label: 'Rosai', type: 'red', source: 'rosai-col-junction', target: 'rhodos-farcis-col-junction',}},
]

// export default [
// 	{ data: { id: 'a', label: 'A' } },
// 	{ data: { id: 'b', label: 'B' } },
// 	{ data: { id: 'c', label: 'C' } },
// 	{ data: { id: 'd', label: 'D' } },

// 	// { data: {id: 'α', source: 'c', target: 'a', type: 'funitel'}},

// 	{ data: {id: '1', source: 'a', target: 'b', type: 'green'}},
// 	{ data: {id: '2', source: 'a', target: 'b', type: 'blue'}},
// 	{ data: {id: '3', source: 'a', target: 'c', type: 'red'}},
// 	{ data: {id: '4', source: 'd', target: 'c', type: 'black'}},
// ]
